pub/protected/controllers/RectangleController.php
<?php

class RectangleController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    /*public $layout='//layouts/column2';*/

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array( //			'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Rectangle;
        $refresh = false;
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Rectangle'])) {
            $model->attributes = $_POST['Rectangle'];
            $model->last_change_date = $model->create_date = Date('Y-m-d H:i:s');
            if ($model->save()) {
                /*echo $this->renderPartial('_message', array());
                return;*/
                $refresh = true;
            }
        }
        echo $this->renderPartial('_form', array(
            'model'         => $model,
            'bindjs'        => empty($_POST['Rectangle']),
            'refresh' => array(
                'history'   => false,
                'rectangle' => $refresh
            )
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $refresh = false;
        $model = $this->loadModel($id);
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Rectangle'])) {
            $model->attributes = $_POST['Rectangle'];
            $model->last_change_date = date('Y-m-d H;:s');
            if ($model->save()) {
                $refresh = true;
                /*echo $this->renderPartial('_message', array());
                return;*/
            }
        }

        echo $this->renderPartial('_form',
            array(
                'model'         => $model,
                'bindjs'        => empty($_POST['Rectangle']),
                'refresh' => array(
                    'history'   => $refresh,
                    'rectangle' => false
                )
            )
        );
    }

    public function actionHistory($id)
    {
        $model = $this->loadModel($id)->getHistoryModel();
        $this->renderPartial('history', array('model' => $model));
    }

    public function actionDetail($id)
    {
        $model = RectangleHistory::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        echo $this->renderPartial('_historyView', array('model' => $model));
    }


    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $this->actionAdmin();
        return;
        $dataProvider = new CActiveDataProvider('Rectangle');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new Rectangle('search');
        $model->unsetAttributes(); // clear any default values
        if (isset($_GET['Rectangle']))
            $model->attributes = $_GET['Rectangle'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     * @return Rectangle
     */
    public function loadModel($id)
    {
        $model = Rectangle::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'rectangle-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

pub/protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{

    public function actionIndex()
    {
        $this->render('index');
    }

    public function actionError()
    {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    public function actionView(){
          //  header("Content-Type: text/javascript");
            header("Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0");

        $answer = array(
            'success' => true,
            'message' => "Loaded data",
            'data' => Users::getAll()
        );

        echo CJSON::encode($answer);
    }

    public function actionCreate(){
        header("Content-Type: text/javascript");

        $answer = array(
            'success' => false,
            'message' => "Created record"
        );

        $data = Yii::app()->request->getPost('Users');

        if (!is_null($data)){
            $user = new Users();
            $user->attributes = $data;
            if ($user->save()){
                $answer = array(
                    'success' => true,
                    'message' => "Loaded data",
                    'data' => $user->attributes
                );
            }
        }

        echo CJSON::encode($answer);
    }

    public function actionUpdate($id){
        header("Content-Type: text/javascript");

        $answer = array(
            'success' => false,
            'message' => "Created record"
        );

        $data = Yii::app()->request->getPost('Users');

        if (!is_null($data)){
            $user = new Users();
            $user->attributes = $data;
            if ($user->save()){
                $answer = array(
                    'success' => true,
                    'message' => "Data are synchronized",
                    'data' => $user->attributes
                );
            }
        }

        echo CJSON::encode($answer);
    }


}

pub/protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

pub/protected/views/site/index.php
<?php
/* @var $this SiteController */

$this->pageTitle = Yii::app()->name;
?>
<h4>Суть задания :</h4>
<p>
    1. Имеется две сущности (два класса, произвольных) с произвольным набором параметров (свойств), разного типа, для
    каждой. Какие-то параметры (свойства) могут описывать обе сущности (например и у дерева и у здания может быть
    параметр/свойство “высота”). Значение любого параметра каждой из сущностей может меняться с течением времени (в
    какую-то дату например).
    Необходимо разработать структуру БД для хранения информации о сущностях и истории изменений их параметров.
    Необходимо предусмотреть возможность выбирать все параметры сущности (экземпляра класса) по состоянию на какой-то
    момент времени (на определенную дату).
</p>
<p>
    2. Необходимо реализовать:
<ul>
    <li>
        Вывод списка экземпляров каждой сущности (два списка), в списке должно показываться 5 любых параметров;
    </li>
    <li>
        Редактирование параметров сущности, с указанием даты изменения параметра (редактирование должно осуществляться
        при помощи Ajax);
    </li>
    <li>
        Удаление экземпляров сущности (удаление должно осуществляться при помощи Ajax);
    </li>
    <li>
        Просмотр состояния сущности на определенную дату.
    </li>
</ul>

<h4>
    Комментарии разработчика
</h4>

    Данное задание выполнено только для одного вида сущностей. Gодозреваю, что в реализации задачи мой потенциальный
работодатель хотел видеть такие элементы ООП как использование базового класса (абстрактного) и использование наследования для создания классов компонентов, а так же
использование одного интерфейса для похожих типов объектов, однако архитектура Yii фреймворка позволяет более удобное
использования подобных сущностей в качестве моделей (экземпляров классов унаследованных от <em>CActiveRecord</em>).
В тесте реализован интерфейс CRUD для некого типа объектов "rectangle"
</p>

<?php
$this->widget('bootstrap.widgets.TbButton', array(
    'label' => Yii::t('app', 'To objective'),
    'type' => 'success', // null, 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
    'size' => 'large', // null, 'large', 'small' or 'mini'*/
    'url' => array('rectangle/index'),
    'ajaxOptions' => array(
        'update' => '#rectangle-form'
    ),
));
?>